### ISSUE TITLE
Publish on Maven

### ISSUE THREAD

**Issue by KrausMatthias** [conveyal/geobuf-java#2]
Hi, 

would it be possible to publish this on Maven? This would save me the additional git clone /mvn install step.

Thanks a lot!

**Comment by landonreed** [comment]
I'm not sure if there are plans to publish this on Maven, but you may be able to use something like https://jitpack.io/ to import the GitHub project directly into your pom.xml.

**Comment by KrausMatthias** [comment]
Thanks! I didn't know jitpack.io :)
